// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2T0xG4HvIKGNFcM_tn13QLbmPnMX5Yoo',
    appId: '1:863480350869:web:67b5a431a71016f926f39c',
    messagingSenderId: '863480350869',
    projectId: 'developed-projects',
    authDomain: 'developed-projects.firebaseapp.com',
    storageBucket: 'developed-projects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6Y4q00GRrrtHID7Bn59eQ9HdVrShXyg',
    appId: '1:863480350869:android:dbdc7e477c3d3eeb26f39c',
    messagingSenderId: '863480350869',
    projectId: 'developed-projects',
    storageBucket: 'developed-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNAZx547LxfeHB0IAw55bgRJiyzKrcmRc',
    appId: '1:863480350869:ios:98b4c35f83d4fffe26f39c',
    messagingSenderId: '863480350869',
    projectId: 'developed-projects',
    storageBucket: 'developed-projects.appspot.com',
    androidClientId: '863480350869-7tpj9l0bh0eljrno9ciiam90gic60inf.apps.googleusercontent.com',
    iosClientId: '863480350869-75b3o8d412kfcfvsg4ju22ldlkkbe15k.apps.googleusercontent.com',
    iosBundleId: 'com.elvis.developedProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNAZx547LxfeHB0IAw55bgRJiyzKrcmRc',
    appId: '1:863480350869:ios:98b4c35f83d4fffe26f39c',
    messagingSenderId: '863480350869',
    projectId: 'developed-projects',
    storageBucket: 'developed-projects.appspot.com',
    androidClientId: '863480350869-7tpj9l0bh0eljrno9ciiam90gic60inf.apps.googleusercontent.com',
    iosClientId: '863480350869-75b3o8d412kfcfvsg4ju22ldlkkbe15k.apps.googleusercontent.com',
    iosBundleId: 'com.elvis.developedProjects',
  );
}
